apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-vq6m
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/fduthill-tenant/my-quarkus-app/devfile-sample-code-with-quarkus-vq6m@sha256:68584025fd096e21ec86cc33f1d0b5e32f0bd5514ffe52cfffb8c98c0adbed7a
        name: my-java-quarkus
        resources: {}
status: {}
